<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_0 (Delete)</name>
   <tag></tag>
   <elementGuidId>3661dc67-0336-4b93-b727-21dc5d988593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-popover-3 > div.a-popover-wrapper > div.a-popover-inner > ul.a-nostyle.a-list-link > li.a-dropdown-item.quantity-option > #quantity_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='quantity_0'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c9eab8f-740f-4611-8d7a-d0313cf6cb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2d08bee1-4645-44c4-b629-902db9842146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>d6bced1c-c1a4-4370-a878-f4fb97b017b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>52f9d9a7-15a2-4f80-bee5-839737a91ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;0&quot;}</value>
      <webElementGuid>1084f8cc-ab6a-40b5-bee2-5f3f6a0cdff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_0</value>
      <webElementGuid>5fdc8dc9-d7b9-46d1-82f9-2b28d83c2449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>53aba55c-bdf5-4ae9-9b9e-1aa9ee1dd3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0 (Delete)</value>
      <webElementGuid>566ed3e3-bc69-4791-8d88-9c4ee2d08d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-popover-3&quot;)/div[@class=&quot;a-popover-wrapper&quot;]/div[@class=&quot;a-popover-inner&quot;]/ul[@class=&quot;a-nostyle a-list-link&quot;]/li[@class=&quot;a-dropdown-item quantity-option&quot;]/a[@id=&quot;quantity_0&quot;]</value>
      <webElementGuid>341aee4e-9877-41c1-8eb4-a468d54e4535</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='quantity_0'])[2]</value>
      <webElementGuid>e93637f6-4240-43f5-9f0d-bb8aec733ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-3']/div/div/ul/li/a</value>
      <webElementGuid>641a21e2-4cda-4e01-bc4d-27d52db739c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'0 (Delete)')])[2]</value>
      <webElementGuid>7a17e196-da0e-4a0b-8c31-821c1be451b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[26]</value>
      <webElementGuid>2f1848a3-a6c4-49a0-999e-43ec20896132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/ul/li/a</value>
      <webElementGuid>40fb42cc-4e82-41ca-a788-dad1275ffdc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'quantity_0' and (text() = '0 (Delete)' or . = '0 (Delete)')]</value>
      <webElementGuid>9b915964-1801-4e4e-969e-fff4cf40a438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
