<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go to Cart</name>
   <tag></tag>
   <elementGuidId>f312d16a-f53f-4aee-9136-279ebb5e7a66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sw-gtc > span.a-button-inner > a.a-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='sw-gtc']/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>841f46c8-adab-4886-bc3a-a094eec7db7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart?ref_=sw_gtc</value>
      <webElementGuid>25a28f2d-a0d2-4a6c-81a1-529fea275294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>sw-gtc_CONTENT</value>
      <webElementGuid>d095cdba-bb4c-4cbf-8a97-11861ed42c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>sw-gtc</value>
      <webElementGuid>876c1835-10ef-40de-aa3e-653e5d57b87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c313deb0-e41f-4e6e-9f8f-e28fff9fb5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>43e42a7a-794b-4476-8154-1a054c01b99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>f61n8r-i5wfmt-mg12nn-mzpmrq</value>
      <webElementGuid>e5e48f9b-b86a-4747-b2b6-88e9423948d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Go to Cart
</value>
      <webElementGuid>8ec7d336-120f-4c88-8a65-bdfb5a5d39a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sw-gtc&quot;)/span[@class=&quot;a-button-inner&quot;]/a[@class=&quot;a-button-text&quot;]</value>
      <webElementGuid>8acdfde4-b2d7-4e7c-96d1-498041c838d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='sw-gtc']/span/a</value>
      <webElementGuid>761a689c-b0c4-4b7a-90cc-da53c88eb41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Go to Cart')])[2]</value>
      <webElementGuid>c2fa5e73-0e43-4593-9438-c98eb6d29204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cart?ref_=sw_gtc')]</value>
      <webElementGuid>4cc799f3-c483-45a5-a2f3-0a3f98ed69a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/span/a</value>
      <webElementGuid>2a467cd5-ebd7-4c44-8f9f-137d5109adaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cart?ref_=sw_gtc' and (text() = '
    Go to Cart
' or . = '
    Go to Cart
')]</value>
      <webElementGuid>a3605373-8385-4b47-ae61-b3367dd0a83c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
