<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Qty1</name>
   <tag></tag>
   <elementGuidId>5cb71c15-3bfd-49cf-b623-751e59e67a5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sc-active-bf8443c6-dabb-47ce-81ff-72ec21d49e6f > div.sc-list-item-content > div.a-row.a-grid-vertical-align.a-grid-top.sc-list-item-content-inner > div.sc-item-content-group > div.a-row.sc-action-links > span.sc-action-quantity > span.sc-invisible-when-no-js > span > span.a-dropdown-container > span.a-button.a-button-dropdown.quantity > span.a-button-inner > span.a-button-text.a-declarative</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sc-active-bf8443c6-dabb-47ce-81ff-72ec21d49e6f']/div[4]/div/div[3]/div/span/span/span/span/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>10aa0d02-6341-41c2-9cb5-7f6e32ccaf21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text a-declarative</value>
      <webElementGuid>4dcf82f2-8045-431e-b114-4f7314d3d57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-func-deps</name>
      <type>Main</type>
      <value>aui-da-a-dropdown-button</value>
      <webElementGuid>4c05df9e-65d0-4bf5-bb90-8d51e0cc9a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>b4f89e1d-35e4-4274-bdef-884761cb4c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-interaction-events</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>0cc833ca-66f9-43d3-be55-5dd52ab4b697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>a-dropdown-button</value>
      <webElementGuid>fd51af21-435b-4d22-86db-175903ac6576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1150ba9-f5ff-4f31-be82-c9cb022b9381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>i8nxta-kckdjq-30c078-pt1s5g</value>
      <webElementGuid>d72f870b-8996-4c06-8e24-10e78c7a1e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qty:1</value>
      <webElementGuid>1d8d3811-acfa-4eed-b10f-8bb215b8a25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-active-bf8443c6-dabb-47ce-81ff-72ec21d49e6f&quot;)/div[@class=&quot;sc-list-item-content&quot;]/div[@class=&quot;a-row a-grid-vertical-align a-grid-top sc-list-item-content-inner&quot;]/div[@class=&quot;sc-item-content-group&quot;]/div[@class=&quot;a-row sc-action-links&quot;]/span[@class=&quot;sc-action-quantity&quot;]/span[@class=&quot;sc-invisible-when-no-js&quot;]/span[1]/span[@class=&quot;a-dropdown-container&quot;]/span[@class=&quot;a-button a-button-dropdown quantity&quot;]/span[@class=&quot;a-button-inner&quot;]/span[@class=&quot;a-button-text a-declarative&quot;]</value>
      <webElementGuid>b2b01779-8bf9-4655-b0f7-4996b7fc1d19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-active-bf8443c6-dabb-47ce-81ff-72ec21d49e6f']/div[4]/div/div[3]/div/span/span/span/span/span/span/span</value>
      <webElementGuid>a28d264d-99c4-4cf5-a5b0-b5505b16336e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div[3]/div/span/span/span/span/span/span/span</value>
      <webElementGuid>9c58e3c9-c2f4-4674-9db2-5fcd3e7e1d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Qty:1' or . = 'Qty:1')]</value>
      <webElementGuid>e743851d-c9da-40c2-bb7e-c1e5144fa87d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
