<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_a-button-input</name>
   <tag></tag>
   <elementGuidId>30d098d7-8116-4b79-a6ce-1fc759f0b1a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#orderSummaryPrimaryActionBtn > span.a-button-inner > input.a-button-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2a1dbf0-a3d3-4ab9-85a9-299689e17910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>25541f2b-11cf-4e84-961f-6192e5472682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>95633817-0ba3-4869-83c1-744cf8320886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>orderSummaryPrimaryActionBtn-announce</value>
      <webElementGuid>99e5fcff-624d-49d6-bbc5-967d67d17bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderSummaryPrimaryActionBtn&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>bc9b0d43-41e3-41fa-9e21-8beeb3de3aa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[6]</value>
      <webElementGuid>b9c85587-b6f8-4436-acbc-6839c877b4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='orderSummaryPrimaryActionBtn']/span/input</value>
      <webElementGuid>20114f81-cab0-48e5-8f3d-33096c433d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span/input</value>
      <webElementGuid>74042cb1-1e1f-45d8-99f0-ebec44bd7c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>fe2e6b5c-4002-428b-96f1-b101b094308d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
