<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputnav-search-submit-button</name>
   <tag></tag>
   <elementGuidId>20f59e8e-3554-47a2-bb88-bc19f48aaf5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-search-submit-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-search-submit-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc2428e4-ed29-4a96-9b3a-9417b2a4ad95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-search-submit-button</value>
      <webElementGuid>118d1f47-5f45-4391-a318-f2194fab42a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>68c1d208-bb60-4e22-a350-b89ddfe6322a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-input nav-progressive-attribute</value>
      <webElementGuid>0ff1658f-d5c4-4ef3-a915-08ca61bd6158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>1b67546b-b831-4b15-8ff7-a308faa2b8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eb7815b7-0358-4510-93b7-e1637032f14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-search-submit-button&quot;)</value>
      <webElementGuid>c166485c-6c9d-4bb9-ac76-5d47737bdbe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-search-submit-button']</value>
      <webElementGuid>eb0c016f-d340-4c8d-ab8f-ca12c499d010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='nav-search-submit-text']/input</value>
      <webElementGuid>99a4ffe9-6a4b-44e5-8246-7c73e7dd8f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>4d1b4a88-ff89-4a9b-a894-b4ba1bc1153d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nav-search-submit-button' and @type = 'submit']</value>
      <webElementGuid>2af92549-2d7f-4788-b95d-9dfc4bc284ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
