<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputinput-box-otp</name>
   <tag></tag>
   <elementGuidId>d4272f6a-aaba-47ce-8815-8a861cf223bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-box-otp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-box-otp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b077441-958a-4197-8aee-c8db06c3305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>d7167215-0ee0-4f08-a475-377d8639dc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>aba1b086-a0f7-4931-ad54-739a9ba5ccca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-box-otp</value>
      <webElementGuid>09df5585-e39a-45b2-ad36-7245fed25aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2ce5f2d3-3004-4114-a480-89fc9871a665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b6038e60-1e1f-47ba-a45e-b9013ca453ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text cvf-widget-input cvf-widget-input-code single-input-box-otp</value>
      <webElementGuid>8e3e44d7-84f8-4c92-8133-3ce815b916e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-box-otp&quot;)</value>
      <webElementGuid>4f8a4e92-a079-4563-8b25-ef3898b0e956</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-box-otp']</value>
      <webElementGuid>31972ccb-cf7c-453a-8c7f-2a06a12f2c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cvf-input-code']/span/div/input</value>
      <webElementGuid>1046987d-4b33-4552-8a3a-7608556b99d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6febdeba-149f-4468-abf4-e051cb14b1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'input-box-otp']</value>
      <webElementGuid>0a50d89b-77d8-44aa-8c98-8ebdfbe588c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
