<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input___sif_encryptedVPA_collect</name>
   <tag></tag>
   <elementGuidId>e994a6f8-8741-419e-aa19-a1ee935dda93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-K4TfIs-135</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-K4TfIs-135']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03e0bb08-0f64-46d5-a607-39a0c39ddca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed4d0867-48ec-488d-8511-d9c92fcd1b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-K4TfIs-135</value>
      <webElementGuid>c659932d-8919-4fbc-8651-5c82f5898cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter UPI ID</value>
      <webElementGuid>47b0d501-0881-4cec-9c1e-051ed138f53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__sif_encryptedVPA_collect</value>
      <webElementGuid>27885bc9-ce0c-496d-899e-0e042f934c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>65041988-0871-499d-9298-927886cd8925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-form-normal no-prefetch-on-change</value>
      <webElementGuid>e524e815-51ed-4211-92ff-95a22333da0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-K4TfIs-135&quot;)</value>
      <webElementGuid>ce47df73-0b1b-4cd5-bf6d-5de8ee089f84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-K4TfIs-135']</value>
      <webElementGuid>394d55d3-81d8-499c-bc75-f2c96fbac92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-K4TfIs-150']/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>43234f6c-c4d2-4a01-9a7a-851ae09c54f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>8c27504a-340b-459e-8fc9-d43494666615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pp-K4TfIs-135' and @placeholder = 'Enter UPI ID' and @name = '__sif_encryptedVPA_collect']</value>
      <webElementGuid>9d9b2c61-0f7d-4d96-83a9-512cca7109bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
