<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ppw-widgetEventValidateUpiIdEvent</name>
   <tag></tag>
   <elementGuidId>02f1d1ec-0a0d-4cd7-a31e-f0e02230403e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ppw-widgetEvent:ValidateUpiIdEvent&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ppw-widgetEvent:ValidateUpiIdEvent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c474fd4-43ce-4777-9830-ddfbc593476f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-widgetEvent:ValidateUpiIdEvent</value>
      <webElementGuid>e616e1e0-27f1-46c4-ac5a-7950c9c07588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input a-button-text</value>
      <webElementGuid>43ef4407-bcab-4337-b7e9-d0ee4e479215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>205e61b2-087d-4a97-81f3-58ac92cd0ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>pp-K4TfIs-136-announce</value>
      <webElementGuid>da467c42-c6d6-4e83-a3ee-0cad05b9d09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-K4TfIs-136&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input a-button-text&quot;]</value>
      <webElementGuid>edb3aa27-28df-4d10-9ebe-761531da851a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ppw-widgetEvent:ValidateUpiIdEvent']</value>
      <webElementGuid>9382f753-15aa-42c2-b38b-ec07476efa00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pp-K4TfIs-136']/span/input</value>
      <webElementGuid>c5efca00-74cb-4ab1-ac12-8f2e4b11da49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/input</value>
      <webElementGuid>a6f50594-4e94-48e3-a8f3-38e2fbc822bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ppw-widgetEvent:ValidateUpiIdEvent' and @type = 'submit']</value>
      <webElementGuid>0c4c4820-c62c-4934-b9c4-f791e90402b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
