<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ppw-instrumentRowSelection</name>
   <tag></tag>
   <elementGuidId>b66b601c-7f4b-473b-9993-f1b7ce9d0d6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-K4TfIs-147</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-K4TfIs-147']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>161ba7d2-1675-4e92-9c3a-9128fa824637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-K4TfIs-147</value>
      <webElementGuid>9da65cf8-8c30-41e6-934f-1d6e76c63e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1ad8b641-fd33-4d41-8976-0adecd4776a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>36afe43f-faf9-46ce-829b-5ece8e025241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=amzn1.pm.poa.YW16bjEucG9hOmFtem4xLnBvYS5wb2RhLlVuaWZpZWRQYXltZW50c0ludGVyZmFjZTox.QTJROVM4U1NYQkJCU1E&amp;isExpired=false&amp;paymentMethod=UnifiedPaymentsInterface&amp;tfxEligible=false</value>
      <webElementGuid>8aa387b5-97fb-46f1-8535-d43b9e4ad4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-K4TfIs-147&quot;)</value>
      <webElementGuid>7730d931-6428-466d-975f-8a5aa1601863</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-K4TfIs-147']</value>
      <webElementGuid>00f9892b-c33d-4629-af68-66c9c9e96f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-K4TfIs-146']/div/div/div/div/div/div/label/input</value>
      <webElementGuid>a46e4105-769d-4554-be0f-73d0214e990e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label/input</value>
      <webElementGuid>6ac86cf9-65b4-4bc4-b835-e1c8f499713c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-K4TfIs-147' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>3671e54a-073e-4d50-81b6-1e5ccd849fb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
