<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_placeYourOrder1</name>
   <tag></tag>
   <elementGuidId>3acbd9b9-5de1-491d-82e2-a3dcc8d1ceab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitOrderButtonId > span.a-button-inner > input[name=&quot;placeYourOrder1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='placeYourOrder1'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fe464ac-614d-4520-9e21-f4e6d73bec38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>placeYourOrder1</value>
      <webElementGuid>bc1925fb-3535-4a96-a0ac-ad919b3fcee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>deaafe31-9461-41a1-a6a8-82c67d1bc9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>208a4068-19c1-4a3a-b3c7-1ca4c863b188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>submitOrderButtonId-announce</value>
      <webElementGuid>04558b51-553f-4d83-b5f9-9a537c037eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitOrderButtonId&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>1b889968-b3e4-47d0-8f56-559f9f8e3585</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='placeYourOrder1'])[3]</value>
      <webElementGuid>76e73baf-b8da-4268-9806-648f268a80dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='submitOrderButtonId']/span/input</value>
      <webElementGuid>c5f0b0f8-4c99-40d9-9e5f-cef1f4f17226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span/span/input</value>
      <webElementGuid>95c99884-b4ba-46d9-b4b2-107f8303047e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'placeYourOrder1' and @type = 'submit']</value>
      <webElementGuid>bbc30e3f-f142-488f-ba1a-d897f7b60e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
