<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_See more product details</name>
   <tag></tag>
   <elementGuidId>ad145569-271a-4b8e-97a1-ab095747403b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#seeMoreDetailsLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='seeMoreDetailsLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>424b40e3-c9a2-4f43-8699-49905b3d7762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>seeMoreDetailsLink</value>
      <webElementGuid>9782a0c5-755f-401e-8639-67c610bf7bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal</value>
      <webElementGuid>f29262a6-04c7-4b32-aedb-9ea82eebeb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#productDetails</value>
      <webElementGuid>bd131795-956f-4e5c-957b-e35b141e067a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> See more product details </value>
      <webElementGuid>905fd94f-1bc1-4700-9ea9-b98bc66e27b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seeMoreDetailsLink&quot;)</value>
      <webElementGuid>8c1cbddb-d55b-4c1d-bc87-c98fb9111721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='seeMoreDetailsLink']</value>
      <webElementGuid>8cb6c537-b3b0-4160-a35b-6f27583ae23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feature-bullets']/a</value>
      <webElementGuid>75fb2768-222b-4f86-b7d0-faaacd27c222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'See more product details')]</value>
      <webElementGuid>2607dba6-0425-4dbd-99d1-7431e9bf4333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#productDetails')]</value>
      <webElementGuid>54479254-35b9-4953-ad1a-f46bd014216f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[48]/div/a</value>
      <webElementGuid>80810ef4-0584-4902-ad91-9e3688fc14b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'seeMoreDetailsLink' and @href = '#productDetails' and (text() = ' See more product details ' or . = ' See more product details ')]</value>
      <webElementGuid>a9978039-8068-4cf2-8982-f6ff07215a0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
